apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-2xtk
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-2xtk
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-2xtk
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-2xtk
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-2xtk
    spec:
      containers:
      - image: quay.io/qijing/ex-registry-hjwo-tenant/appstudio/dc-metro-map-2xtk@sha256:191716495d6d5f134bb79c52cb60cc1a3ab4ed86ee0539238cb5ea0f6e725074
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
